package _6_;

public class JavaShutdownHook {
    public static void main(String args[]) {
        Runtime r = Runtime.getRuntime();
        r.addShutdownHook(new Thread() {
            public void run() {
                System.out.println("Shutdown task1");
            }
        });

        r.addShutdownHook(new Thread() {
            public void run() {
                System.out.println("Shutdown task2");
            }
        });

        r.addShutdownHook(new Thread() {
            public void run() {
                System.out.println("Shutdown task3");
            }
        });

        System.out.println(
                "This program is an illustration of shutdown hook. You can press Ctrl +C to end this program.");
        for (int i = 0; i >= 0; i++) {
            System.out.println(i + "...");
            try {
                Thread.currentThread().sleep(1000);
            } catch (Exception e) {
                System.out.println(e);
            }

        }
    }

}
/*
ubuntu@ubuntu-linux:~/Documents/college/AdvancedJavaMA/Assignment6$  cd /home/ubuntu/Documents/college/AdvancedJavaMA/Assignment6 ; /usr/bin/env /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Dfile.encoding=UTF-8 -cp /home/ubuntu/.config/Code/User/workspaceStorage/0e7b35696775f25fd31f418aae959ecd/redhat.java/jdt_ws/Assignment6_449183e8/bin _6_.JavaShutdownHook 
This program is an illustration of shutdown hook. You can press Ctrl +C to end this program.
0...
1...
2...
3...
4...
5...
6...
7...
8...
9...
10...
11...
12...
13...
14...
15...
16...
17...
18...
19...
20...
21...
22...
23...
24...
25...
26...
27...
28...
29...
^CShutdown task2
Shutdown task3
Shutdown task1
*/